version: '3'
services:
  mockify:
    build: .
    env_file:
      - .env
    environment:
      - MOCKIFY_PORT=8001
      - MOCKIFY_ROUTES=./config/routes.yaml
    volumes:
      - ./app:/app
    ports:
      - "${MOCKIFY_PORT}:${MOCKIFY_PORT}"
